version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/LtiAdvantage.AspNetCore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/LtiAdvantage.IdentityModel"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/LtiAdvantage.Oidc"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/LtiAdvantage"
    schedule:
      interval: "weekly"
