name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: XUnit Tests                  # Name of the check run which will be created
        path: '*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results
        list-suites: all
        list-tests: all